# Generated by Django 2.0.10 on 2019-01-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('spiel', models.TextField(null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Season')),
            ],
        ),
    ]
